UPBGE: Use userprefs to load addons in blenderplayer
UPBGE/upbge pull request #1389
Opened 2021-01-28 21:12 UTC by youle31

Addons need to read userpref.blend file to know which addons are
registered.

It allows to use registered addons in blendeprlayer.

If no userpref.blend is found, default user preferences are
loaded.

Code picked from wm_files > wm_homefile_read

2021-01-28 22:28 UTC, lordloki requested changes
Other that commented code seems me ok. I will test when i modify the addon

2021-01-28 22:28 UTC, lordloki commented on source/gameengine/GamePlayer/GPG_ghost.cpp
> +    BLI_path_join(filepath_userdef, sizeof(filepath_startup), cfgdir, BLENDER_USERPREF_FILE, NULL);
filepath_startup is really used?

Additionally, I think there is typo as it should be:
BLI_path_join(filepath_userdef, sizeof(**filepath_userdef**), cfgdir, BLENDER_USERPREF_FILE, NULL);

2021-01-28 22:48 UTC, youle31 commented
Yes sorry it was a copy/paste from wm_files without changes, i did the requested changes, Thanks for the review!

2021-01-28 23:19 UTC, lordloki approved these changes
Great!! I just pushed the save_as_runtime addon modification to copy userpref.blend

2021-01-28 23:40 UTC, mysticfall commented
It works perfectly for me. Thanks much! :)

2021-01-28 23:40 UTC, mysticfall approved these changes

2021-01-29 00:00 UTC, youle31 commented
Perfect! Thanks very much for review!

I'm not 100% sure that the priority goes to exported game folder but my test protocol was messy, then if there's an issue with priorities, we'll fix it later.

Thanks both for review and tests and for the addon! I merge that

2021-01-29 00:00 UTC, merged